### ISSUE TITLE
[Crash]: I believe that the stoneworks mod is causing my game to crash due to the cycling of the icons on the tab in the creative menu. I apologize if it is not the stoneworks mod, I am not good at understanding crash logs but it is my best guess. (It appears to be conflicting with your puzzles lib mod that is required for it)

### ISSUE THREAD

**Issue by 2iqPlays** [Fuzss/stoneworks#6] opened 2023-09-04 15:39 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.0.1

### Notes (Required)

Open Creative Inventory Screen
Scroll To Stoneworks Tab
Wait Until Stoneworks Tab Icon Scrolls To Basalt
Game Crashes After Basalt Icon

### Crash Report (Required)

https://gist.github.com/2iqPlays/950a652b18c180856ee359419559beb4

**Comment by Fuzss** [comment] 2023-09-11 06:04
Duplicate of #5.

**Closed by Fuzss** 2023-09-11 06:04 UTC
Labels: bug
